require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DoorsController do

  # This should return the minimal set of attributes required to create a valid
  # Door. As you add validations to Door, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "day" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DoorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all doors as @doors" do
      door = Door.create! valid_attributes
      get :index, {}, valid_session
      assigns(:doors).should eq([door])
    end
  end

  describe "GET show" do
    it "assigns the requested door as @door" do
      door = Door.create! valid_attributes
      get :show, {:id => door.to_param}, valid_session
      assigns(:door).should eq(door)
    end
  end

  describe "GET new" do
    it "assigns a new door as @door" do
      get :new, {}, valid_session
      assigns(:door).should be_a_new(Door)
    end
  end

  describe "GET edit" do
    it "assigns the requested door as @door" do
      door = Door.create! valid_attributes
      get :edit, {:id => door.to_param}, valid_session
      assigns(:door).should eq(door)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Door" do
        expect {
          post :create, {:door => valid_attributes}, valid_session
        }.to change(Door, :count).by(1)
      end

      it "assigns a newly created door as @door" do
        post :create, {:door => valid_attributes}, valid_session
        assigns(:door).should be_a(Door)
        assigns(:door).should be_persisted
      end

      it "redirects to the created door" do
        post :create, {:door => valid_attributes}, valid_session
        response.should redirect_to(Door.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved door as @door" do
        # Trigger the behavior that occurs when invalid params are submitted
        Door.any_instance.stub(:save).and_return(false)
        post :create, {:door => { "day" => "invalid value" }}, valid_session
        assigns(:door).should be_a_new(Door)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Door.any_instance.stub(:save).and_return(false)
        post :create, {:door => { "day" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested door" do
        door = Door.create! valid_attributes
        # Assuming there are no other doors in the database, this
        # specifies that the Door created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Door.any_instance.should_receive(:update_attributes).with({ "day" => "1" })
        put :update, {:id => door.to_param, :door => { "day" => "1" }}, valid_session
      end

      it "assigns the requested door as @door" do
        door = Door.create! valid_attributes
        put :update, {:id => door.to_param, :door => valid_attributes}, valid_session
        assigns(:door).should eq(door)
      end

      it "redirects to the door" do
        door = Door.create! valid_attributes
        put :update, {:id => door.to_param, :door => valid_attributes}, valid_session
        response.should redirect_to(door)
      end
    end

    describe "with invalid params" do
      it "assigns the door as @door" do
        door = Door.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Door.any_instance.stub(:save).and_return(false)
        put :update, {:id => door.to_param, :door => { "day" => "invalid value" }}, valid_session
        assigns(:door).should eq(door)
      end

      it "re-renders the 'edit' template" do
        door = Door.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Door.any_instance.stub(:save).and_return(false)
        put :update, {:id => door.to_param, :door => { "day" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested door" do
      door = Door.create! valid_attributes
      expect {
        delete :destroy, {:id => door.to_param}, valid_session
      }.to change(Door, :count).by(-1)
    end

    it "redirects to the doors list" do
      door = Door.create! valid_attributes
      delete :destroy, {:id => door.to_param}, valid_session
      response.should redirect_to(doors_url)
    end
  end

end
